/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.rb-root[_ngcontent-%COMP%] {\n    padding: 5pt;\n    border-radius: 5px;\n    border: 1pt solid #555;\n    background-color: #eee;\n    font-family: Verdata,sans-serif;\n}\nh1[_ngcontent-%COMP%] {\n    font-size: 120%;\n    font-weight: 700;\n    color: #339;\n}\nh2[_ngcontent-%COMP%] {\n    font-size: 110%;\n    font-weight: 700;\n    color: #339;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUva2FybC9zZWFnYXRlL3Jlc3QtYnVuZGxlL3NyYy91aS9hcHAvcmVzdF9idW5kbGUubW9kdWxlLmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL2thcmwvc2VhZ2F0ZS9yZXN0LWJ1bmRsZS9zcmMvdWkvYXBwL2luZGV4X2xpbmsuY29tcG9uZW50LnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
