/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './rest_bundle.module.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../app/rest_bundle.component';
const styles_RestBundleComponent:any[] = [import0.styles];
export const RenderType_RestBundleComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_RestBundleComponent,
  data: {}
}
);
export function View_RestBundleComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
      (l()(),import1.ɵeld(0,(null as any),(null as any),3,'div',[[
        'class',
        'rb-root'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[
      '<',
      '>'
    ]
    )),
    (l()(),import1.ɵted((null as any),[
      '',
      ''
    ]
    ))
  ]
  ,(null as any),(ck,v) => {
    var co:import2.RestBundleComponent = v.component;
    const currVal_0:any = co.name;
    ck(v,2,0,currVal_0);
    const currVal_1:any = co.date;
    ck(v,3,0,currVal_1);
  });
}
function View_RestBundleComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'rest-bundle-ui',([] as any[]),(null as any),(null as any),(null as any),View_RestBundleComponent_0,RenderType_RestBundleComponent)),
    import1.ɵdid(24576,(null as any),0,import2.RestBundleComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const RestBundleComponentNgFactory:import1.ComponentFactory<import2.RestBundleComponent> = import1.ɵccf('rest-bundle-ui',import2.RestBundleComponent,View_RestBundleComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUva2FybC9zZWFnYXRlL3Jlc3QtYnVuZGxlL3NyYy91aS9hcHAvcmVzdF9idW5kbGUuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUva2FybC9zZWFnYXRlL3Jlc3QtYnVuZGxlL3NyYy91aS9hcHAvcmVzdF9idW5kbGUuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS9rYXJsL3NlYWdhdGUvcmVzdC1idW5kbGUvc3JjL3VpL2FwcC9yZXN0X2J1bmRsZS5jb21wb25lbnQudHMuUmVzdEJ1bmRsZUNvbXBvbmVudC5odG1sIiwibmc6Ly8vaG9tZS9rYXJsL3NlYWdhdGUvcmVzdC1idW5kbGUvc3JjL3VpL2FwcC9yZXN0X2J1bmRsZS5jb21wb25lbnQudHMuUmVzdEJ1bmRsZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJyYi1yb290XCI+PGgxPiZsdDt7e25hbWV9fSZndDs8L2gxPnt7ZGF0ZX19PC9kaXY+IiwiPHJlc3QtYnVuZGxlLXVpPjwvcmVzdC1idW5kbGUtdWk+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7TUNBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXFCO0lBQUk7TUFBQTtNQUFBO0lBQUE7SUFBQTtJQUFxQjtNQUFBO01BQUE7SUFBQTtJQUFBOzs7O0lBQXJCO0lBQUE7SUFBcUI7SUFBQTs7Ozs7SUNBOUM7Z0JBQUE7Ozs7In0=
